// <auto-generated />
using System;
using MatchPet.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchPet.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MatchPetDbContext))]
    partial class MatchPetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MatchPet.Shared.Models.AdoptForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AgreesWithResponsibilities")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AllowedRooms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AnimalHabitat")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyRoutine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HadPetsInThePast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasChildrenAtHome")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasOtherAnimalsAtHome")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HouseholdMembersAwareAndAgree")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HouseholdMembersCount")
                        .HasColumnType("int");

                    b.Property<bool>("LivingInSaoPaulo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtherAnimalsDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PetAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PetFood")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsiblePerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VetClinic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AdoptForms");
                });

            modelBuilder.Entity("MatchPet.Shared.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsReadyTo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSterilized")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUnderTreatment")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ShelterSince")
                        .HasColumnType("datetime");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("SupportType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("MatchPet.Shared.Models.SponsorForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RecurringBilling")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SponsorForms");
                });
#pragma warning restore 612, 618
        }
    }
}
