namespace MatchPet.Shared.Models;

public enum AnimalHabitatType
{
  HOUSE_WITHOUT_AUTOMATIC_GATE,
  HOUSE_WITH_AUTOMATIC_GATE,
  HOUSE_WITH_POOL,
  APARTMENT_WITH_PROTECTIVE_SCREENS,
  APARTMENT_WITHOUT_PROTECTIVE_SCREENS
}