x-project-name: &project-name docker-compose-matchpet
name: *project-name

networks:
  matchpet:
    driver: bridge
    name: matchpet

services:
#  api:
#    build:
#      context: ..
#      dockerfile: Dockerfile
#    container_name: matchpet-api
#    ports:
#      - "8080:80"
#    depends_on:
#      - mysql
#    environment:
#      - MYSQL_MATCHPET_CONNECTION_STRING=Server=localhost;Port=3306;Database=matchpet;Uid=root;Pwd=root;SSL Mode=None;
#    networks:
#      - matchpet
  
  mysql:
    image: mysql:9.0
    container_name: matchpet-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matchpet
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - matchpet
  
  adminer:
    image: adminer
    container_name: matchpet-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - matchpet

volumes:
  mysql-data: